[package]
name = "kickstart"
version = "0.2.0"
description = "A simple way to get started with a project"
authors = ["Vincent Prouillet <hello@vincentprouillet.com>"]
license = "MIT"
edition = "2018"

[dependencies]
clap = "2"
tera = "1"
walkdir = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
memchr = "2"
glob = "0.3"
regex = "1"
term = "0.6"

[dev-dependencies]
tempfile = "3"

[badges]
maintenance = { status = "actively-developed" }
