[package]
name = "kickstart"
version = "0.1.8"
description = "A simple way to get started with a project"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
license = "MIT"

[dependencies]
clap = "2"
tera = "1.0.0-beta.21"
walkdir = "2"
serde_derive = "1"
serde = "1"
toml = "0.5"
memchr = "2"
glob = "0.3"
regex = "1"
term = "0.6"

[dev-dependencies]
tempfile = "3"
