[package]
name = "kickstart"
version = "0.1.5"
description = "A simple way to get started with a project"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
license = "MIT"

[[bin]]
name = "kickstart"

[dependencies]
clap = "2"
tera = "0.11"
walkdir = "2"
serde_derive = "1"
serde = "1"
toml = "0.4"
memchr = "2"
glob = "0.2"
regex = "1"
term = "0.5"

[dev-dependencies]
tempfile = "3"
