[bin_name]
default = "Bin"
question = "Binary name?"

[description]
default = "Some CLI app"
question = "A description for that binary?"

[author_name]
default = "Vincent"
question = "Your name?"

[author_mail]
default = "spam@spam.com"
question = "Your email?"

[use_clap]
default = true
question = "Do you want clap set-up?"
