[directory_name]
default = "Hello"
question = "Directory name?"

[file_name]
default = "Howdy"
question = "File name?"

[greeting_recipient]
default = "Vincent"
question = "Who am I greeting?"

[database]
default = "postgres"
question = "Which database do you want to use?"
choices = [
    "postgres",
    "mysql",
    "sqlite",
]
